CREATE TABLE <databaseName>.scall(`DateTime` DateTime64(6,'Europe/Moscow'),
                                  `duration` Int32,
                                  `Level` Int32,
                                  `Process` String,
                                  `ProcessID` Int32,
                                  `ProcessName` String,
                                  `OSThread` Int32,
                                  `ClientID` Int32,
                                  `ApplicationName` String,
                                  `ComputerName` String,
                                  `SessionID` Int32,
                                  `User` String,
                                  `Method` String,
                                  `IName` String,
                                  `MName` String,
                                  `Interface` String,
                                  `DstClientID` Int32,
                                  `CallID` Int32,
                                  `Context` String,
                                  `message` String,
                                  `file` String) ENGINE = MergeTree() PARTITION BY toYYYYMM(DateTime)
ORDER BY (DateTime);