CREATE TABLE <databaseName>.excpcntx(`DateTime` DateTime,
                                  `duration` Int32,
                                  `Level` Int32,
                                  `ClientComputerName` String,
                                  `ServerComputerName` String,
                                  `UserName` String,
                                  `ConnectString` String,
                                  `SrcName` String,
                                  `Process` String,
                                  `ProcessID` Int32,
                                  `ProcessName` String,
                                  `OSThread` Int32,
                                  `ClientID` Int32,
                                  `ApplicationName` String,
                                  `ComputerName` String,
                                  `ConnectID` Int32,
                                  `SessionID` Int32,
                                  `User` String,
                                  `DBMS` String,
                                  `DataBase` String,
                                  `Trans` String,
                                  `Function` String,
                                  `callWait` String,
                                  `first` String,
                                  `Module` String,
                                  `Method` String,
                                  `Sdbl` String,
                                  `CallID` Int32,
                                  `Context` String) ENGINE = MergeTree() PARTITION BY toYYYYMM(DateTime)
ORDER BY (DateTime);