CREATE TABLE <databaseName>.`call`(`DateTime` DateTime64(6,'Europe/Moscow'),
                                  `duration` Int32,
                                  `Level` Int32,
                                  `Process` String,
                                  `ProcessID` Int32,
                                  `ProcessName` String,
                                  `OSThread` Int32,
                                  `ClientID` Int32,
                                  `ApplicationName` String,
                                  `ComputerName` String,
                                  `CallWait` Int32,
                                  `First` String,
                                  `SessionID` Int32,
                                  `User` String,
                                  `Function` String,
                                  `Module` String,
                                  `Method` String,
                                  `Report` String,
                                  `IName` String,
                                  `MName` String,
                                  `Interface` String,
                                  `DstClientID` Int32,
                                  `CallID` Int32,
                                  `Memory` Int32,
                                  `MemoryPeak` Int32,
                                  `InBytes` Int32,
                                  `OutBytes` Int32,
                                  `CpuTime` Int32,
                                  `Context` String,
                                  `message` String,
                                  `file` String) ENGINE = MergeTree() PARTITION BY toYYYYMM(DateTime)
ORDER BY (DateTime);